### ISSUE TITLE
Basic example

### ISSUE THREAD

**Issue by hyanwong** [hyanwong/GeneticInheritanceGraphLibrary#2]
Before [creating a GIG simulator](#3 ), it would probably be useful to have a demo GIG that we can reason about.

**Comment by hyanwong** [comment]
Here's an example for a single tree. I think we should maintain the `tskit` idea of assigning times to nodes, and using integer IDs
## edges
| parent | child | child_left | child_right | parent_left | parent_right |
|--------|-------|------------|-------------|-------------|--------------|
| 6      | 0     | 0          | 300         | 0           | 300          |
| 6      | 1     | 0          | 300         | 0           | 300          |
| 9      | 6     | 0          | 200         | 0           | 200          |
| 9      | 6     | 200        | 300         | 100         | 200               |
| 11     | 9     | 0          | 200         | 0           | 200          |
| 7      | 2     | 0          | 100         | 0           | 100          |
| 7      | 3     | 0          | 100         | 0           | 100          |
| 10     | 7     | 0          | 50          | 0           | 50           |
| 10     | 7     | 50         | 100         | 150         | 200          |
| 11     | 10    | 0          | 200         | 0           | 200          |
| 8      | 4     | 0          | 200         | 0           | 200          |
| 8      | 5     | 0          | 200         | 0           | 200          |
| 12     | 8     | 0          | 80          | 0           | 80           |
| 12     | 8     | 80         | 120         | 120         | 80           |
| 12     | 8     | 120        | 200         | 120         | 200          |
| 12     | 11    | 0          | 200         | 0           | 200          |

## Nodes
| id | time | sample
|--------|-------|------------|
| 0 | 0 | Y |
| 1 | 0 | Y |
| 2 | 0 | Y |
| 3 | 0 | Y |
| 4 | 0 | Y |
| 5 | 0 | Y |
| 6 | 1 | N |
| 7 | 2 | N |
| 8 | 2 | N |
| 9 | 3 | N |
| 10 | 4 | N |
| 11 | 5 | N |
| 12 | 6 | N |


Here's how that would look in networkx (duplication on left, deletion in middle, inversion on right)

```python
import networkx as nx
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import itertools


# create a Pandas DataFrame from the parent-child data
edges = pd.DataFrame({
    'parent': [6, 6, 9, 9, 11, 7, 7, 10, 10, 11, 8, 8, 12, 12, 12, 12],
    'child': [0, 1, 6, 6, 9, 2, 3, 7, 7, 10, 4, 5, 8, 8, 8, 11],
    'child_left': [0, 0, 0, 200, 0, 0, 0, 0, 50, 0, 0, 0, 0, 80, 120, 0],
    'child_right': [300, 300, 200, 300, 200, 100, 100, 50, 100, 200, 200, 200, 80, 120, 200, 200],
    'parent_left': [0, 0, 0, 100, 0, 0, 0, 0, 150, 0, 0, 0, 0, 120, 120, 0],
    'parent_right': [300, 300, 200, 200, 200, 100, 100, 50, 200, 200, 200, 200, 80, 80, 200, 200],
})


edges["parent_interval"] = [f"{e.parent_left}…{e.parent_right}" for e in edges.itertuples()]
edges["child_interval"] =  [f"{e.child_left}…{e.child_right}" for e in edges.itertuples()]

print(edges)

nodes = pd.DataFrame({'id': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        'time': [0, 0, 0, 0, 0, 0, 1, 2, 2, 3, 4, 5, 6],
        'sample': ['Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N']})


# create a directed graph from the DataFrame
G = nx.from_pandas_edgelist(
    edges,
    source='parent',
    target='child',
    edge_attr=["parent_interval", "child_interval"],
    create_using=nx.MultiDiGraph())

fig, ax = plt.subplots(1, 1, figsize=(10, 10))
A = nx.nx_agraph.to_agraph(G)
for r in (nodes.groupby('time')['id'].apply(list)).items():
    A.add_subgraph(r[1], level="same", name=f"cluster{r[0]}")
A.layout(prog="dot")
pos = {n: [float(x) for x in A.get_node(n).attr["pos"].split(",")] for n in G.nodes()}
pos = {node_id: np.array([pos[node_id][0], nodes.loc[node_id].time]) for node_id in nodes.id}
nx.draw_networkx_nodes(G, pos, nodelist=[n.id for n in nodes.itertuples() if n.sample == "Y"], ax=ax, node_size=500, node_shape="s")
nx.draw_networkx_nodes(G, pos, nodelist=[n.id for n in nodes.itertuples() if n.sample != "Y"], ax=ax, node_size=500)
nx.draw_networkx_labels(G, pos, ax=ax)

for (parent, child), e in itertools.groupby(G.edges(keys=True,data=True), key=lambda x: (x[0], x[1])):
    e = list([edge[3] for edge in e])
    curves = [0] if len(e) == 1 else np.linspace(-1, 1, len(e))
    for edge, curve in zip(e, curves):
        ax.annotate("",
            xy=pos[parent], xycoords='data',
            xytext=pos[child], textcoords='data',
            arrowprops=dict(
                arrowstyle="->", color="0.5",
                shrinkA=5, shrinkB=5,
                patchA=None, patchB=None,
                connectionstyle="arc3,rad=rrr".replace('rrr',str(0.2*curve)),
                ),
            )
        ax.text(
            (pos[parent][0]-pos[child][0])*(0.25 if curve == 0 else 0.2) + curve * 20 + pos[child][0],
            (pos[parent][1]-pos[child][1])*(0.25 if curve == 0 else 0.2) + pos[child][1],
            str(edge['child_interval']),
            ha="center",
            bbox=dict(facecolor='white', edgecolor='none', pad=0.1))
        ax.text(
            (pos[parent][0]-pos[child][0])*(0.75 if curve == 0 else 0.8) + curve * 20 + pos[child][0],
            (pos[parent][1]-pos[child][1])*(0.75 if curve == 0 else 0.8) + pos[child][1],
            str(edge['parent_interval']),
            ha="center",
            bbox=dict(facecolor='white', edgecolor='none', pad=0.1))

# show the plot
plt.axis('off')
plt.show()
```

![image](https://user-images.githubusercontent.com/4699014/229593417-03adcf2d-d8c7-44eb-af5f-31959076dab3.png)

**Comment by hyanwong** [comment]
Also see #5 about placing mutations on this structure

**Comment by duncanMR** [comment]
@hyanwong I wanted to work out this example by hand, just like we did on the whiteboard once. I thought of three ways to represent the GIG. The first one conveys the same info as your nifty networkx plot. I've added a couple of mutations to help figure the mutation placement issue out.

![image](https://github.com/hyanwong/GeneticInheritanceGraph/assets/5416474/0fff67b3-71e7-4ed5-895a-140a06f49940)

I wanted to visualise what happens to chunks of the genome in each structural change. The one mutation I added happens before the duplication at x = 180 (above node 9), so it is duplicated to x = 280 as well. The other mutation happens after the duplication at x = 110 (above node 0), so it is not present at x = 210 too. This highlights your point in #5 that we can't define a global sites table; the site of each mutation has to be in the coordinate system of the node below it.

 We can abstract this further by defining functions for each type of structural change, as to the right of the graph below

![image](https://github.com/hyanwong/GeneticInheritanceGraph/assets/5416474/ff799921-92d8-4f81-9a6f-304e1f99e43a)

Each color corresponds to a group of nodes that are connected by identity edges, meaning that I have the same coordinate system. I think this means that we can define a tree sequence for each coloured group. Hence, we can abstract further by combining nodes of the same color.

![image](https://github.com/hyanwong/GeneticInheritanceGraph/assets/5416474/97df6528-a10a-4db7-a73c-6edc85d01167)

Now it is clear to see that we have four distinct tree sequences in this case. What are they? Let's start with the coordinate system of the root node:

![image](https://github.com/hyanwong/GeneticInheritanceGraph/assets/5416474/aa83fdaf-ac0c-49ed-abcb-1c6b1ff22169)

Here, the ⮌I symbol indicates that that edge is inverting coordinates.  The nodes 6, 0 and 1 are duplicated to 6*, 0* and 1*, with the understanding that starred nodes are in the same genome as their non-starred counterparts. I've tried to think of a way to avoid having to do something like this, but I haven't figured it out. Now let's look at the nodes with duplications.

![image](https://github.com/hyanwong/GeneticInheritanceGraph/assets/5416474/4c31a415-ca1f-4fa7-8f04-f7985ff28c18)

We no longer need to add 6*, 0* and 1* because our coordinate system includes the duplicated region. This only means that x = 100 is not a breakpoint here, unlike all the other sequences. We see the duplicated mutation at x = 180 and x = 280; in fact the sequence from 100-200 simply repeats for 200-300.  Turning to the opposite extreme, let's look at the nodes with a genome size of only 100.

![image](https://github.com/hyanwong/GeneticInheritanceGraph/assets/5416474/e9a2db06-88f6-4cb2-a599-fa736d270881)

This one can be obtained from the root node sequence by just cutting out the chunk from 50-150 and renumbering the mutation. Finally, let's look at the inverted nodes. 

![image](https://github.com/hyanwong/GeneticInheritanceGraph/assets/5416474/545decb2-acf3-46b3-842c-fa42c303ee7e)

This one can be obtained from the root TS by flipping around the trees between x = 80 and x = 160.

## Conclusions

The GIG model directly leads to the idea of local tree sequences which share the same coordinate system. These local tree sequences seem to differ from the standard tskit ones in the following ways:

- The number of sample nodes can increase or decrease as you move along the sequence, due to duplications and deletions, respectively.
- There are two distinct types of edges; normal ones, and inverted ones. To make matters more complicated, inverted edges have parameters: the start and end of the genomic region which is inverted. 

The main advantage of using a local TS is that we can define an edges table with the usual left, right, parent and child columns. At a minimum, I think we'll need one more column to encode inversions somehow. The challenge will be to see how well we can adapt the abundance of tskit algorithms to this new type of TS. I'm hoping to start exploring that soon.

Finally, I think we should be able to write algorithms to go from one local tree sequence to another by using the structure of the GIG. Just like we can go from one tree to another in a TS by adding and removing edges, so could we go from one local TS to another by adding and removing trees and renumbering.

**Comment by hyanwong** [comment]
Great observation about defining clusters of nodes with the same coordinate system. It may get complicated when generalising to a more graph-like structure, but the general idea is there, I think. Some internal nodes may be able to be classified into multiple coordinate systems, so that your summary above:

![image](https://github.com/hyanwong/GeneticInheritanceGraph/assets/5416474/97df6528-a10a-4db7-a73c-6edc85d01167)

may consist of overlapping sets, rather than distinct sets of coordinate systems.

**Comment by duncanMR** [comment]
That's a good point. If we introduce recombination into the mix, figuring out the coordinate systems will get even more confusing!

**Comment by hyanwong** [comment]
This example is coded up as `all_sv_types_gig` at https://github.com/hyanwong/GeneticInheritanceGraph/blob/fed4fe10e96e683980c83cb19fd4a75a5123f246/tests/conftest.py#L37

Note that it is *not* sample resolved, because the edge from 10 -> 11 has no genetic material from samples between positions 50..150.

**Comment by hyanwong** [comment]
We have this example in the

**Comment by hyanwong** [comment]
Here is the updated plot from the [ProbGen poster](https://docs.google.com/presentation/d/1MRSsV6HWFb2zoXq34QO3YtjqWqa4Z6JXfkiGWNt8kaU/edit#slide=id.g2c80a1b4356_0_237) <img width="1000" alt="Screenshot 2024-04-19 at 17 37 51" src="https://github.com/hyanwong/GeneticInheritanceGraphLibrary/assets/4699014/1d4fc832-380d-4347-8566-3dd331df8015">
