### ISSUE TITLE
Changes to tskit-like API

### ISSUE THREAD

**Issue by hyanwong** [hyanwong/GeneticInheritanceGraphLibrary#49]
There are a few differences between the API for GIGlib and tskit. It's probably worth noting them down somewhere for an FAQ.

One that I'm not sure about is whether we should encourage the more Pythonic `len(gig.edges)` instead of the tskit-like `gig.num_edges`. I'm inclined to go with the former?

**Comment by duncanMR** [comment]
Using `len` also means we don't have to create more properties, so I agree that it's simpler that way. I'll make a note to post here if we change `tskit` conventions again. Most of the differences I can think of are either due to the new complexities of the data structure or are just missing features that we haven't ported over yet.

**Comment by hyanwong** [comment]
Documented in the main README (https://github.com/hyanwong/GeneticInheritanceGraphLibrary#api-differences). Closing
